-- Generated by scripts/generate-authoritative-mimma-seed.mts. Do not edit.
-- dataset_version: authoritative-mimma-seed-v1
-- source: data/surnex-dataset.csv

CREATE TABLE authoritative_mimma_seeds (
  id TEXT PRIMARY KEY NOT NULL,
  conceptual_name TEXT NOT NULL COLLATE NOCASE UNIQUE,
  micro_score INTEGER NOT NULL CHECK (typeof(micro_score) = 'integer' AND micro_score BETWEEN 0 AND 100),
  meso_score INTEGER NOT NULL CHECK (typeof(meso_score) = 'integer' AND meso_score BETWEEN 0 AND 100),
  macro_score INTEGER NOT NULL CHECK (typeof(macro_score) = 'integer' AND macro_score BETWEEN 0 AND 100),
  provenance TEXT NOT NULL CHECK (provenance = 'authoritative_sample_seed'),
  dataset_version TEXT NOT NULL CHECK (dataset_version = 'authoritative-mimma-seed-v1'),
  created_at TEXT NOT NULL,
  CHECK (
    (micro_score = 100 AND meso_score = 0 AND macro_score = 0) OR
    (micro_score = 0 AND meso_score = 100 AND macro_score = 0) OR
    (micro_score = 0 AND meso_score = 0 AND macro_score = 100)
  )
);
--> statement-breakpoint

CREATE TRIGGER authoritative_mimma_seeds_prevent_update
BEFORE UPDATE ON authoritative_mimma_seeds
BEGIN
  SELECT RAISE(ABORT, 'authoritative MiMMa seeds are immutable');
END;
--> statement-breakpoint

CREATE TRIGGER authoritative_mimma_seeds_prevent_delete
BEFORE DELETE ON authoritative_mimma_seeds
BEGIN
  SELECT RAISE(ABORT, 'authoritative MiMMa seeds cannot be deleted');
END;
--> statement-breakpoint

INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-7-billion-humans', '7 Billion Humans', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-adventure-capitalist', 'AdVenture Capitalist', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-aimlabs', 'Aimlabs', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-among-us', 'Among Us', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-beat-saber', 'Beat Saber', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-blood-on-the-clocktower', 'Blood on the Clocktower', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-cities-skylines', 'Cities: Skylines', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-clicker-heroes', 'Clicker Heroes', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-codenames', 'Codenames', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-connect-4', 'Connect 4', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-cookie-clicker', 'Cookie Clicker', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-coup', 'Coup', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-crossy-road', 'Crossy Road', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-crusader-kings-iii', 'Crusader Kings III', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-cs2-surf', 'CS2 Surf', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-dark-roll', 'Dark Roll', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-devil-daggers', 'Devil Daggers', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-dwarf-fortress', 'Dwarf Fortress', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-f-zero-gx', 'F-Zero GX', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-factorio', 'Factorio', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-flappy-bird', 'Flappy Bird', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-friday-night-funkin', 'Friday Night Funkin''', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-gambling-slots', 'Gambling / Slots', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-geometry-dash', 'Geometry Dash', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-goose-goose-duck', 'Goose Goose Duck', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-grand-theft-auto-v', 'Grand Theft Auto V', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-guess-who', 'Guess Who?', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-half-sword', 'Half Sword', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-hot-lava', 'Hot Lava', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-i-wanna-be-the-guy', 'I Wanna Be the Guy', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-kerbal-space-program', 'Kerbal Space Program', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-liars-bar', 'Liar''s Bar', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-liars-dice', 'Liar''s Dice', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-mafia', 'Mafia', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-mini-motorways', 'Mini Motorways', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-osu', 'osu!', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-oxygen-not-included', 'Oxygen Not Included', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-poly-bridge', 'Poly Bridge', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-project-winter', 'Project Winter', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-qwop', 'QWOP', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-rimworld', 'RimWorld', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-rock-paper-scissors', 'Rock Paper Scissors', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-satisfactory', 'Satisfactory', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-shapez', 'shapez', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-simcity', 'SimCity', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-spyfall', 'Spyfall', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-stardew-valley', 'Stardew Valley', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-stepmania', 'StepMania', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-stock-trading', 'Stock Trading', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-subway-surfers', 'Subway Surfers', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-sudoku', 'Sudoku', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-super-hexagon', 'Super Hexagon', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-super-mario-maker', 'Super Mario Maker', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-super-meat-boy', 'Super Meat Boy', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-superhot', 'SUPERHOT', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-taiko-no-tatsujin', 'Taiko no Tatsujin', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-tetris', 'Tetris', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-the-resistance-avalon', 'The Resistance: Avalon', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-tic-tac-toe', 'Tic-Tac-Toe', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-town-of-salem', 'Town of Salem', 0, 100, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-typeracer', 'TypeRacer', 100, 0, 0, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint
INSERT INTO authoritative_mimma_seeds (id, conceptual_name, micro_score, meso_score, macro_score, provenance, dataset_version, created_at) VALUES ('authoritative-mimma-seed-v1-victoria-3', 'Victoria 3', 0, 0, 100, 'authoritative_sample_seed', 'authoritative-mimma-seed-v1', '2026-08-18T20:02:44Z');
--> statement-breakpoint

CREATE TRIGGER authoritative_mimma_seeds_prevent_insert
BEFORE INSERT ON authoritative_mimma_seeds
BEGIN
  SELECT RAISE(ABORT, 'authoritative MiMMa seed set is immutable');
END;
--> statement-breakpoint
