-- Generated by scripts/generate-owner-authoritative-mimma.mts. Do not edit.
-- source_manifest_version: owner-authoritative-mimma-v1
-- source_hash: da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65

CREATE TABLE authoritative_games (
  id TEXT PRIMARY KEY NOT NULL CHECK (id GLOB 'auth-game-*'),
  identity_key TEXT NOT NULL COLLATE NOCASE UNIQUE CHECK (
    length(identity_key) > 0 AND
    identity_key NOT GLOB '*[^a-z0-9-]*' AND
    identity_key NOT LIKE '-%' AND identity_key NOT LIKE '%-' AND identity_key NOT LIKE '%--%'
  ),
  canonical_title TEXT NOT NULL COLLATE NOCASE UNIQUE CHECK (length(trim(canonical_title)) > 0),
  introduced_manifest_version TEXT NOT NULL CHECK (length(trim(introduced_manifest_version)) > 0),
  introduced_source_hash TEXT NOT NULL CHECK (
    length(introduced_source_hash) = 64 AND
    introduced_source_hash NOT GLOB '*[^0-9a-f]*'
  ),
  created_on TEXT NOT NULL CHECK (created_on GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]')
);
--> statement-breakpoint
CREATE TABLE authoritative_mimma_score_versions (
  id TEXT PRIMARY KEY NOT NULL,
  game_id TEXT NOT NULL REFERENCES authoritative_games(id) ON DELETE RESTRICT,
  version INTEGER NOT NULL CHECK (typeof(version) = 'integer' AND version > 0),
  micro_score INTEGER NOT NULL CHECK (typeof(micro_score) = 'integer' AND micro_score BETWEEN 0 AND 100),
  meso_score INTEGER NOT NULL CHECK (typeof(meso_score) = 'integer' AND meso_score BETWEEN 0 AND 100),
  macro_score INTEGER NOT NULL CHECK (typeof(macro_score) = 'integer' AND macro_score BETWEEN 0 AND 100),
  micro_original_decimal TEXT NOT NULL CHECK (
    micro_original_decimal NOT GLOB '*[^0-9.]*' AND length(micro_original_decimal) BETWEEN 3 AND 5 AND
    instr(micro_original_decimal, '.') = length(micro_original_decimal) - 1 AND
    (length(micro_original_decimal) = 3 OR substr(micro_original_decimal, 1, 1) <> '0') AND
    CAST(replace(micro_original_decimal, '.', '') AS INTEGER) BETWEEN 0 AND 1000
  ),
  meso_original_decimal TEXT NOT NULL CHECK (
    meso_original_decimal NOT GLOB '*[^0-9.]*' AND length(meso_original_decimal) BETWEEN 3 AND 5 AND
    instr(meso_original_decimal, '.') = length(meso_original_decimal) - 1 AND
    (length(meso_original_decimal) = 3 OR substr(meso_original_decimal, 1, 1) <> '0') AND
    CAST(replace(meso_original_decimal, '.', '') AS INTEGER) BETWEEN 0 AND 1000
  ),
  macro_original_decimal TEXT NOT NULL CHECK (
    macro_original_decimal NOT GLOB '*[^0-9.]*' AND length(macro_original_decimal) BETWEEN 3 AND 5 AND
    instr(macro_original_decimal, '.') = length(macro_original_decimal) - 1 AND
    (length(macro_original_decimal) = 3 OR substr(macro_original_decimal, 1, 1) <> '0') AND
    CAST(replace(macro_original_decimal, '.', '') AS INTEGER) BETWEEN 0 AND 1000
  ),
  decimal_scale INTEGER NOT NULL CHECK (decimal_scale = 1),
  rounding_mode TEXT NOT NULL CHECK (rounding_mode = 'half-up-to-integer-v1'),
  source_manifest_version TEXT NOT NULL CHECK (length(trim(source_manifest_version)) > 0),
  source_hash TEXT NOT NULL CHECK (
    length(source_hash) = 64 AND source_hash NOT GLOB '*[^0-9a-f]*'
  ),
  provenance TEXT NOT NULL CHECK (provenance = 'owner_authoritative'),
  approval_reason TEXT NOT NULL CHECK (approval_reason IN ('initial-owner-snapshot', 'owner-correction', 'owner-restore')),
  approved_on TEXT NOT NULL CHECK (approved_on GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  UNIQUE (game_id, version),
  UNIQUE (id, game_id),
  CHECK (micro_score <> 0 OR meso_score <> 0 OR macro_score <> 0),
  CHECK (micro_score <> 100 OR meso_score <> 100 OR macro_score <> 100)
);
--> statement-breakpoint
CREATE TABLE authoritative_snapshots (
  id TEXT PRIMARY KEY NOT NULL,
  version INTEGER NOT NULL UNIQUE CHECK (typeof(version) = 'integer' AND version > 0),
  manifest_version TEXT NOT NULL CHECK (length(trim(manifest_version)) > 0),
  source_hash TEXT NOT NULL CHECK (
    length(source_hash) = 64 AND source_hash NOT GLOB '*[^0-9a-f]*'
  ),
  expected_member_count INTEGER NOT NULL CHECK (typeof(expected_member_count) = 'integer' AND expected_member_count > 0),
  state TEXT NOT NULL CHECK (state IN ('draft', 'frozen')),
  created_on TEXT NOT NULL CHECK (created_on GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  frozen_on TEXT,
  CHECK ((state = 'draft' AND frozen_on IS NULL) OR (state = 'frozen' AND frozen_on IS NOT NULL AND frozen_on GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'))
);
--> statement-breakpoint
CREATE TABLE authoritative_snapshot_members (
  snapshot_id TEXT NOT NULL REFERENCES authoritative_snapshots(id) ON DELETE RESTRICT,
  game_id TEXT NOT NULL REFERENCES authoritative_games(id) ON DELETE RESTRICT,
  score_id TEXT NOT NULL,
  PRIMARY KEY (snapshot_id, game_id),
  UNIQUE (snapshot_id, score_id),
  FOREIGN KEY (score_id, game_id) REFERENCES authoritative_mimma_score_versions(id, game_id) ON DELETE RESTRICT
);
--> statement-breakpoint
CREATE TABLE authoritative_game_mappings (
  id TEXT PRIMARY KEY NOT NULL,
  game_id TEXT NOT NULL REFERENCES authoritative_games(id) ON DELETE RESTRICT,
  provider TEXT NOT NULL CHECK (length(provider) > 0 AND provider = lower(provider) AND provider NOT GLOB '*[^a-z0-9_-]*'),
  external_id TEXT NOT NULL CHECK (length(external_id) > 0),
  catalog_game_id TEXT NOT NULL REFERENCES games(id) ON DELETE RESTRICT,
  mapping_version INTEGER NOT NULL CHECK (typeof(mapping_version) = 'integer' AND mapping_version > 0),
  decision TEXT NOT NULL CHECK (decision IN ('verified', 'rejected', 'revoked')),
  verification_ref TEXT NOT NULL CHECK (length(trim(verification_ref)) > 0),
  supersedes_mapping_id TEXT REFERENCES authoritative_game_mappings(id) ON DELETE RESTRICT,
  source_manifest_version TEXT NOT NULL CHECK (length(trim(source_manifest_version)) > 0),
  source_hash TEXT NOT NULL CHECK (
    length(source_hash) = 64 AND source_hash NOT GLOB '*[^0-9a-f]*'
  ),
  decided_on TEXT NOT NULL CHECK (decided_on GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'),
  UNIQUE (game_id, provider, mapping_version),
  UNIQUE (id, game_id, provider, mapping_version)
);
--> statement-breakpoint
CREATE INDEX authoritative_mimma_score_versions_game_version_idx ON authoritative_mimma_score_versions(game_id, version DESC);
--> statement-breakpoint
CREATE INDEX authoritative_snapshots_state_version_idx ON authoritative_snapshots(state, version DESC);
--> statement-breakpoint
CREATE INDEX authoritative_game_mappings_game_provider_version_idx ON authoritative_game_mappings(game_id, provider, mapping_version DESC);
--> statement-breakpoint
CREATE INDEX authoritative_game_mappings_provider_external_version_idx ON authoritative_game_mappings(provider, external_id, mapping_version DESC);
--> statement-breakpoint
CREATE INDEX authoritative_game_mappings_catalog_version_idx ON authoritative_game_mappings(catalog_game_id, mapping_version DESC);
--> statement-breakpoint
CREATE TRIGGER authoritative_games_prevent_update
BEFORE UPDATE ON authoritative_games
BEGIN
  SELECT RAISE(ABORT, 'authoritative games are immutable');
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_games_prevent_delete
BEFORE DELETE ON authoritative_games
BEGIN
  SELECT RAISE(ABORT, 'authoritative games cannot be deleted');
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_mimma_score_versions_prevent_update
BEFORE UPDATE ON authoritative_mimma_score_versions
BEGIN
  SELECT RAISE(ABORT, 'authoritative score versions are immutable');
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_mimma_score_versions_prevent_delete
BEFORE DELETE ON authoritative_mimma_score_versions
BEGIN
  SELECT RAISE(ABORT, 'authoritative score versions cannot be deleted');
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_snapshots_freeze_guard
BEFORE UPDATE ON authoritative_snapshots
WHEN OLD.state = 'draft' AND NEW.state = 'frozen'
BEGIN
  SELECT RAISE(ABORT, 'snapshot freeze requires complete membership')
  WHERE NEW.frozen_on IS NULL
    OR (SELECT COUNT(*) FROM authoritative_snapshot_members WHERE snapshot_id = NEW.id) <> NEW.expected_member_count
    OR (SELECT COUNT(DISTINCT game_id) FROM authoritative_snapshot_members WHERE snapshot_id = NEW.id) <> NEW.expected_member_count
    OR (SELECT COUNT(DISTINCT score_id) FROM authoritative_snapshot_members WHERE snapshot_id = NEW.id) <> NEW.expected_member_count;
  SELECT RAISE(ABORT, 'snapshot identity is immutable')
  WHERE NEW.id <> OLD.id OR NEW.version <> OLD.version OR NEW.manifest_version <> OLD.manifest_version
    OR NEW.source_hash <> OLD.source_hash OR NEW.expected_member_count <> OLD.expected_member_count
    OR NEW.created_on <> OLD.created_on;
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_snapshots_prevent_frozen_update
BEFORE UPDATE ON authoritative_snapshots
WHEN OLD.state = 'frozen' OR NOT (OLD.state = 'draft' AND NEW.state = 'frozen')
BEGIN
  SELECT RAISE(ABORT, 'authoritative snapshots are immutable');
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_snapshots_prevent_delete
BEFORE DELETE ON authoritative_snapshots
BEGIN
  SELECT RAISE(ABORT, 'authoritative snapshots cannot be deleted');
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_snapshot_members_prevent_frozen_insert
BEFORE INSERT ON authoritative_snapshot_members
WHEN (SELECT state FROM authoritative_snapshots WHERE id = NEW.snapshot_id) <> 'draft'
BEGIN
  SELECT RAISE(ABORT, 'snapshot members can only be inserted into a draft');
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_snapshot_members_prevent_update
BEFORE UPDATE ON authoritative_snapshot_members
BEGIN
  SELECT RAISE(ABORT, 'authoritative snapshot members are immutable');
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_snapshot_members_prevent_delete
BEFORE DELETE ON authoritative_snapshot_members
BEGIN
  SELECT RAISE(ABORT, 'authoritative snapshot members cannot be deleted');
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_game_mappings_prevent_update
BEFORE UPDATE ON authoritative_game_mappings
BEGIN
  SELECT RAISE(ABORT, 'authoritative mapping history is immutable');
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_game_mappings_prevent_delete
BEFORE DELETE ON authoritative_game_mappings
BEGIN
  SELECT RAISE(ABORT, 'authoritative mapping history cannot be deleted');
END;
--> statement-breakpoint
CREATE TRIGGER authoritative_game_mappings_insert_guard
BEFORE INSERT ON authoritative_game_mappings
BEGIN
  SELECT RAISE(ABORT, 'Steam mapping does not match catalog identity')
  WHERE NEW.provider = 'steam' AND NOT EXISTS (
    SELECT 1 FROM games AS g
    WHERE g.id = NEW.catalog_game_id AND CAST(g.steam_app_id AS TEXT) = NEW.external_id
  );
  SELECT RAISE(ABORT, 'mapping versions must be contiguous')
  WHERE NEW.mapping_version <> COALESCE((
    SELECT MAX(mapping_version) + 1 FROM authoritative_game_mappings
    WHERE game_id = NEW.game_id AND provider = NEW.provider
  ), 1);
  SELECT RAISE(ABORT, 'mapping version 1 cannot supersede a row')
  WHERE NEW.mapping_version = 1 AND NEW.supersedes_mapping_id IS NOT NULL;
  SELECT RAISE(ABORT, 'mapping supersession must name the prior same-game row')
  WHERE NEW.mapping_version > 1 AND NOT EXISTS (
    SELECT 1 FROM authoritative_game_mappings AS prior
    WHERE prior.id = NEW.supersedes_mapping_id AND prior.game_id = NEW.game_id
      AND prior.provider = NEW.provider AND prior.mapping_version = NEW.mapping_version - 1
  );
END;
--> statement-breakpoint
-- verify catalog Steam identities before authority inserts
--> statement-breakpoint
SELECT id, steam_app_id FROM games WHERE id IN ('steam-730', 'steam-1623730', 'steam-2767030', 'steam-1172470', 'steam-359550', 'steam-1086940', 'steam-2246340', 'steam-1245620') ORDER BY id;
--> statement-breakpoint
SELECT COUNT(*) FROM authoritative_mimma_scores;
--> statement-breakpoint
INSERT INTO authoritative_games (id, identity_key, canonical_title, introduced_manifest_version, introduced_source_hash, created_on) VALUES ('auth-game-counter-strike-2', 'counter-strike-2', 'Counter-Strike 2', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_games (id, identity_key, canonical_title, introduced_manifest_version, introduced_source_hash, created_on) VALUES ('auth-game-palworld', 'palworld', 'Palworld', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_games (id, identity_key, canonical_title, introduced_manifest_version, introduced_source_hash, created_on) VALUES ('auth-game-marvel-rivals', 'marvel-rivals', 'Marvel Rivals', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_games (id, identity_key, canonical_title, introduced_manifest_version, introduced_source_hash, created_on) VALUES ('auth-game-apex-legends', 'apex-legends', 'Apex Legends', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_games (id, identity_key, canonical_title, introduced_manifest_version, introduced_source_hash, created_on) VALUES ('auth-game-rainbow-six-siege', 'rainbow-six-siege', 'Tom Clancy''s Rainbow Six Siege', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_games (id, identity_key, canonical_title, introduced_manifest_version, introduced_source_hash, created_on) VALUES ('auth-game-baldurs-gate-3', 'baldurs-gate-3', 'Baldur''s Gate 3', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_games (id, identity_key, canonical_title, introduced_manifest_version, introduced_source_hash, created_on) VALUES ('auth-game-monster-hunter-wilds', 'monster-hunter-wilds', 'Monster Hunter Wilds', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_games (id, identity_key, canonical_title, introduced_manifest_version, introduced_source_hash, created_on) VALUES ('auth-game-elden-ring', 'elden-ring', 'ELDEN RING', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_games (id, identity_key, canonical_title, introduced_manifest_version, introduced_source_hash, created_on) VALUES ('auth-game-league-of-legends', 'league-of-legends', 'League of Legends', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_games (id, identity_key, canonical_title, introduced_manifest_version, introduced_source_hash, created_on) VALUES ('auth-game-valorant', 'valorant', 'Valorant', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_mimma_score_versions (id, game_id, version, micro_score, meso_score, macro_score, micro_original_decimal, meso_original_decimal, macro_original_decimal, decimal_scale, rounding_mode, source_manifest_version, source_hash, provenance, approval_reason, approved_on) VALUES ('auth-score-counter-strike-2-v1', 'auth-game-counter-strike-2', 1, 100, 65, 80, '100.0', '65.0', '80.0', 1, 'half-up-to-integer-v1', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', 'owner_authoritative', 'initial-owner-snapshot', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_mimma_score_versions (id, game_id, version, micro_score, meso_score, macro_score, micro_original_decimal, meso_original_decimal, macro_original_decimal, decimal_scale, rounding_mode, source_manifest_version, source_hash, provenance, approval_reason, approved_on) VALUES ('auth-score-palworld-v1', 'auth-game-palworld', 1, 40, 20, 70, '40.0', '20.0', '70.0', 1, 'half-up-to-integer-v1', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', 'owner_authoritative', 'initial-owner-snapshot', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_mimma_score_versions (id, game_id, version, micro_score, meso_score, macro_score, micro_original_decimal, meso_original_decimal, macro_original_decimal, decimal_scale, rounding_mode, source_manifest_version, source_hash, provenance, approval_reason, approved_on) VALUES ('auth-score-marvel-rivals-v1', 'auth-game-marvel-rivals', 1, 80, 60, 80, '80.0', '60.0', '80.0', 1, 'half-up-to-integer-v1', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', 'owner_authoritative', 'initial-owner-snapshot', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_mimma_score_versions (id, game_id, version, micro_score, meso_score, macro_score, micro_original_decimal, meso_original_decimal, macro_original_decimal, decimal_scale, rounding_mode, source_manifest_version, source_hash, provenance, approval_reason, approved_on) VALUES ('auth-score-apex-legends-v1', 'auth-game-apex-legends', 1, 80, 80, 100, '80.0', '80.0', '100.0', 1, 'half-up-to-integer-v1', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', 'owner_authoritative', 'initial-owner-snapshot', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_mimma_score_versions (id, game_id, version, micro_score, meso_score, macro_score, micro_original_decimal, meso_original_decimal, macro_original_decimal, decimal_scale, rounding_mode, source_manifest_version, source_hash, provenance, approval_reason, approved_on) VALUES ('auth-score-rainbow-six-siege-v1', 'auth-game-rainbow-six-siege', 1, 80, 60, 80, '80.0', '60.0', '80.0', 1, 'half-up-to-integer-v1', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', 'owner_authoritative', 'initial-owner-snapshot', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_mimma_score_versions (id, game_id, version, micro_score, meso_score, macro_score, micro_original_decimal, meso_original_decimal, macro_original_decimal, decimal_scale, rounding_mode, source_manifest_version, source_hash, provenance, approval_reason, approved_on) VALUES ('auth-score-baldurs-gate-3-v1', 'auth-game-baldurs-gate-3', 1, 20, 20, 100, '20.0', '20.0', '100.0', 1, 'half-up-to-integer-v1', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', 'owner_authoritative', 'initial-owner-snapshot', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_mimma_score_versions (id, game_id, version, micro_score, meso_score, macro_score, micro_original_decimal, meso_original_decimal, macro_original_decimal, decimal_scale, rounding_mode, source_manifest_version, source_hash, provenance, approval_reason, approved_on) VALUES ('auth-score-monster-hunter-wilds-v1', 'auth-game-monster-hunter-wilds', 1, 80, 40, 60, '80.0', '40.0', '60.0', 1, 'half-up-to-integer-v1', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', 'owner_authoritative', 'initial-owner-snapshot', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_mimma_score_versions (id, game_id, version, micro_score, meso_score, macro_score, micro_original_decimal, meso_original_decimal, macro_original_decimal, decimal_scale, rounding_mode, source_manifest_version, source_hash, provenance, approval_reason, approved_on) VALUES ('auth-score-elden-ring-v1', 'auth-game-elden-ring', 1, 80, 100, 40, '80.0', '100.0', '40.0', 1, 'half-up-to-integer-v1', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', 'owner_authoritative', 'initial-owner-snapshot', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_mimma_score_versions (id, game_id, version, micro_score, meso_score, macro_score, micro_original_decimal, meso_original_decimal, macro_original_decimal, decimal_scale, rounding_mode, source_manifest_version, source_hash, provenance, approval_reason, approved_on) VALUES ('auth-score-league-of-legends-v1', 'auth-game-league-of-legends', 1, 69, 77, 100, '68.6', '77.1', '100.0', 1, 'half-up-to-integer-v1', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', 'owner_authoritative', 'initial-owner-snapshot', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_mimma_score_versions (id, game_id, version, micro_score, meso_score, macro_score, micro_original_decimal, meso_original_decimal, macro_original_decimal, decimal_scale, rounding_mode, source_manifest_version, source_hash, provenance, approval_reason, approved_on) VALUES ('auth-score-valorant-v1', 'auth-game-valorant', 1, 100, 73, 80, '100.0', '73.3', '80.0', 1, 'half-up-to-integer-v1', 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', 'owner_authoritative', 'initial-owner-snapshot', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_snapshots (id, version, manifest_version, source_hash, expected_member_count, state, created_on, frozen_on) VALUES ('snapshot-owner-authoritative-mimma-v1', 1, 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', 10, 'draft', '2026-08-21', NULL);
--> statement-breakpoint
INSERT INTO authoritative_snapshot_members (snapshot_id, game_id, score_id) VALUES ('snapshot-owner-authoritative-mimma-v1', 'auth-game-counter-strike-2', 'auth-score-counter-strike-2-v1');
--> statement-breakpoint
INSERT INTO authoritative_snapshot_members (snapshot_id, game_id, score_id) VALUES ('snapshot-owner-authoritative-mimma-v1', 'auth-game-palworld', 'auth-score-palworld-v1');
--> statement-breakpoint
INSERT INTO authoritative_snapshot_members (snapshot_id, game_id, score_id) VALUES ('snapshot-owner-authoritative-mimma-v1', 'auth-game-marvel-rivals', 'auth-score-marvel-rivals-v1');
--> statement-breakpoint
INSERT INTO authoritative_snapshot_members (snapshot_id, game_id, score_id) VALUES ('snapshot-owner-authoritative-mimma-v1', 'auth-game-apex-legends', 'auth-score-apex-legends-v1');
--> statement-breakpoint
INSERT INTO authoritative_snapshot_members (snapshot_id, game_id, score_id) VALUES ('snapshot-owner-authoritative-mimma-v1', 'auth-game-rainbow-six-siege', 'auth-score-rainbow-six-siege-v1');
--> statement-breakpoint
INSERT INTO authoritative_snapshot_members (snapshot_id, game_id, score_id) VALUES ('snapshot-owner-authoritative-mimma-v1', 'auth-game-baldurs-gate-3', 'auth-score-baldurs-gate-3-v1');
--> statement-breakpoint
INSERT INTO authoritative_snapshot_members (snapshot_id, game_id, score_id) VALUES ('snapshot-owner-authoritative-mimma-v1', 'auth-game-monster-hunter-wilds', 'auth-score-monster-hunter-wilds-v1');
--> statement-breakpoint
INSERT INTO authoritative_snapshot_members (snapshot_id, game_id, score_id) VALUES ('snapshot-owner-authoritative-mimma-v1', 'auth-game-elden-ring', 'auth-score-elden-ring-v1');
--> statement-breakpoint
INSERT INTO authoritative_snapshot_members (snapshot_id, game_id, score_id) VALUES ('snapshot-owner-authoritative-mimma-v1', 'auth-game-league-of-legends', 'auth-score-league-of-legends-v1');
--> statement-breakpoint
INSERT INTO authoritative_snapshot_members (snapshot_id, game_id, score_id) VALUES ('snapshot-owner-authoritative-mimma-v1', 'auth-game-valorant', 'auth-score-valorant-v1');
--> statement-breakpoint
INSERT INTO authoritative_game_mappings (id, game_id, provider, external_id, catalog_game_id, mapping_version, decision, verification_ref, supersedes_mapping_id, source_manifest_version, source_hash, decided_on) VALUES ('auth-map-steam-counter-strike-2-v1', 'auth-game-counter-strike-2', 'steam', '730', 'steam-730', 1, 'verified', 'owner-approved-manifest-v1', NULL, 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_game_mappings (id, game_id, provider, external_id, catalog_game_id, mapping_version, decision, verification_ref, supersedes_mapping_id, source_manifest_version, source_hash, decided_on) VALUES ('auth-map-steam-palworld-v1', 'auth-game-palworld', 'steam', '1623730', 'steam-1623730', 1, 'verified', 'owner-approved-manifest-v1', NULL, 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_game_mappings (id, game_id, provider, external_id, catalog_game_id, mapping_version, decision, verification_ref, supersedes_mapping_id, source_manifest_version, source_hash, decided_on) VALUES ('auth-map-steam-marvel-rivals-v1', 'auth-game-marvel-rivals', 'steam', '2767030', 'steam-2767030', 1, 'verified', 'owner-approved-manifest-v1', NULL, 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_game_mappings (id, game_id, provider, external_id, catalog_game_id, mapping_version, decision, verification_ref, supersedes_mapping_id, source_manifest_version, source_hash, decided_on) VALUES ('auth-map-steam-apex-legends-v1', 'auth-game-apex-legends', 'steam', '1172470', 'steam-1172470', 1, 'verified', 'owner-approved-manifest-v1', NULL, 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_game_mappings (id, game_id, provider, external_id, catalog_game_id, mapping_version, decision, verification_ref, supersedes_mapping_id, source_manifest_version, source_hash, decided_on) VALUES ('auth-map-steam-rainbow-six-siege-v1', 'auth-game-rainbow-six-siege', 'steam', '359550', 'steam-359550', 1, 'verified', 'owner-approved-manifest-v1', NULL, 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_game_mappings (id, game_id, provider, external_id, catalog_game_id, mapping_version, decision, verification_ref, supersedes_mapping_id, source_manifest_version, source_hash, decided_on) VALUES ('auth-map-steam-baldurs-gate-3-v1', 'auth-game-baldurs-gate-3', 'steam', '1086940', 'steam-1086940', 1, 'verified', 'owner-approved-manifest-v1', NULL, 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_game_mappings (id, game_id, provider, external_id, catalog_game_id, mapping_version, decision, verification_ref, supersedes_mapping_id, source_manifest_version, source_hash, decided_on) VALUES ('auth-map-steam-monster-hunter-wilds-v1', 'auth-game-monster-hunter-wilds', 'steam', '2246340', 'steam-2246340', 1, 'verified', 'owner-approved-manifest-v1', NULL, 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
INSERT INTO authoritative_game_mappings (id, game_id, provider, external_id, catalog_game_id, mapping_version, decision, verification_ref, supersedes_mapping_id, source_manifest_version, source_hash, decided_on) VALUES ('auth-map-steam-elden-ring-v1', 'auth-game-elden-ring', 'steam', '1245620', 'steam-1245620', 1, 'verified', 'owner-approved-manifest-v1', NULL, 'owner-authoritative-mimma-v1', 'da26d8f94ebbc932bc6cb7ea70591a19ab316e028f8bc013dcb0fbb8356a9a65', '2026-08-21');
--> statement-breakpoint
UPDATE authoritative_snapshots SET state = 'frozen', frozen_on = '2026-08-21' WHERE id = 'snapshot-owner-authoritative-mimma-v1' AND state = 'draft';
