import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { format, resolveConfig } from 'prettier'

import type { CatalogRelease, CatalogReleaseGame } from '../src/shared/catalog-contract.js'

interface CatalogReleaseValidator {
  assertValidCatalogRelease(release: unknown): CatalogRelease
}

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const releasePath = resolve(repositoryRoot, 'data/catalog-release-v1.json')
const seedPath = resolve(repositoryRoot, 'migrations/0002_seed_beta_catalog.sql')
const snapshotPath = resolve(repositoryRoot, 'src/ui/generated/catalog-snapshot.ts')

function sqlString(value: string | number): string {
  return `'${String(value).replaceAll("'", "''")}'`
}

function toSnapshotGame(game: CatalogReleaseGame) {
  return {
    authoritativeScore: null,
    id: game.id,
    provenance: game.provenance,
    review: game.review,
    shortDescription: game.shortDescription,
    slug: game.slug,
    steamAppId: game.steamAppId,
    tags: game.tags,
    title: game.title,
  }
}

export function renderSeedSql(release: CatalogRelease): string {
  const statements = release.games.map((game) => {
    const values = [
      game.id,
      game.slug,
      game.steamAppId,
      game.title,
      game.steamTitle,
      game.shortDescription,
      JSON.stringify(game.tags),
      game.review.category,
      game.review.count,
      game.review.scope,
      game.admission.path,
      game.provenance.appDetailsUrl,
      game.provenance.storePageUrl,
      game.provenance.fetchedAt,
      game.titleMapping?.explanation ?? null,
    ]
      .map((value: string | number | null) => (value === null ? 'NULL' : sqlString(value)))
      .join(', ')

    return `INSERT INTO games (id, slug, steam_app_id, title, steam_title, short_description, source_tags_json, review_category, review_count, review_scope, catalog_status, source_app_details_url, source_store_page_url, source_fetched_at, title_mapping_note) VALUES (${values});`
  })

  return `-- Generated by scripts/generate-catalog-artifacts.mts. Do not edit.\n-- dataset_version: ${release.datasetVersion}\n-- schema_version: ${release.schemaVersion}\n\nINSERT INTO catalog_release_metadata (dataset_version, schema_version, generated_at) VALUES (${sqlString(release.datasetVersion)}, ${release.schemaVersion}, ${sqlString(release.generatedAt)});\n\n${statements.join('\n')}\n`
}

export async function renderSnapshot(release: CatalogRelease): Promise<string> {
  const snapshot = {
    datasetVersion: release.datasetVersion,
    generatedAt: release.generatedAt,
    games: release.games.map(toSnapshotGame),
    schemaVersion: release.schemaVersion,
  }

  const source = `// Generated by scripts/generate-catalog-artifacts.mts. Do not edit.\nimport type { CatalogSnapshot } from '../../shared/catalog-contract.js'\n\nexport const catalogSnapshot = ${JSON.stringify(snapshot, null, 2)} as const satisfies CatalogSnapshot\n`
  const prettierOptions = (await resolveConfig(snapshotPath)) ?? {}

  return format(source, { ...prettierOptions, filepath: snapshotPath })
}

async function getCatalogReleaseValidator(): Promise<CatalogReleaseValidator> {
  const validatorModuleUrl = new URL('./validate-catalog-release.mts', import.meta.url).href
  return (await import(validatorModuleUrl)) as CatalogReleaseValidator
}

export async function generateCatalogArtifacts(release: unknown) {
  const validator = await getCatalogReleaseValidator()
  const validRelease = validator.assertValidCatalogRelease(release)
  return {
    seedSql: renderSeedSql(validRelease),
    snapshot: await renderSnapshot(validRelease),
  }
}

function readRelease(): unknown {
  return JSON.parse(readFileSync(releasePath, 'utf8')) as unknown
}

function writeArtifact(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content, 'utf8')
}

function assertArtifactMatches(path: string, expected: string): void {
  const actual = (() => {
    try {
      return readFileSync(path, 'utf8')
    } catch {
      throw new Error(`Generated artifact is missing: ${path}`)
    }
  })()

  if (actual !== expected) {
    throw new Error(
      `Generated artifact drift detected: ${path}. Run node scripts/generate-catalog-artifacts.mts --write.`,
    )
  }
}

async function main() {
  const artifacts = await generateCatalogArtifacts(readRelease())
  if (process.argv.includes('--write')) {
    writeArtifact(seedPath, artifacts.seedSql)
    writeArtifact(snapshotPath, artifacts.snapshot)
    process.stdout.write('Catalog artifacts generated.\n')
    return
  }

  assertArtifactMatches(seedPath, artifacts.seedSql)
  assertArtifactMatches(snapshotPath, artifacts.snapshot)
  process.stdout.write('Catalog artifacts match the release manifest.\n')
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main()
}
